version: "3.7"

services:
 #test:
 #  image: nvidia/cuda:12.2.0-base-ubuntu20.04
 #  command: nvidia-smi
 #  deploy:
 #    resources:
 #      reservations:
 #        devices:
 #          - driver: nvidia
 #            count: 1
 #            capabilities: [gpu]


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - net

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: "db"
      #MONGO_INITDB_ROOT_USERNAME: "root"
      #MONGO_INITDB_ROOT_PASSWORD: "myBigDevPassword!"

    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - net
      
volumes:
  ollama_data:
    driver: local
  mongo_data:
    driver: local

networks:
  net:
    driver: bridge
